### ISSUE TITLE
Press Release Too Far Down

### ISSUE THREAD

**Issue by ryanleesipes** [OpenSeedINC/leafletbomb#85]
Press releases are too far down, it does highlight the featured picture but really shuns the written content. We should adjust this.

![toofardown](https://user-images.githubusercontent.com/2141621/32087822-bca54096-ba9b-11e7-94ea-f52d5a37b481.png)

![toofardown2](https://user-images.githubusercontent.com/2141621/32087823-c194e4bc-ba9b-11e7-9bb9-147c46359e97.png)

**Comment by bflanagin** [comment]
we'll try to split the difference between what we have now, and what I thought looked good and #50 which is what we have now.

**Comment by bflanagin** [comment]
Tweaked from 500px to 360px.

**Comment by ryanleesipes** [comment]
Looks better in the Newsroom, but still looks really far down in the editor.

![in_editor](https://user-images.githubusercontent.com/2141621/32113615-0f6326a6-bafe-11e7-8aba-d54e72f4505e.png)

**Comment by bflanagin** [comment]
hmmm, Okay, I tweaked it again. I'm using a percentage value instead of a Pixel count. But Now it looks right in both the editor and the  newsroom.

The variable can be found in /posts/post_Item.js "topPadding" if you want to tweak it more.  We use post_Item.html and its javascript file buddy everywhere there is a post.

**Comment by ryanleesipes** [comment]
The newsroom looks great! I guess I think the Dashboard looks too far down now. Haha.

**Comment by bflanagin** [comment]
A lot of it might depend on the featured image as well. On one of my machines the difference is hardly noticeable. 

We could change it so that the padding is aware of what area its in to adjust it to be exactly the same. I'll see about messing around with it today.

**Comment by ryanleesipes** [comment]
Thank you @bflanagin
